Django_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = "accounts"
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name="profile"),
    #Django Auth
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')

]

Django_website/apps/contact/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import contact


app_name = "contact"

urlpatterns = [

    path("", contact, name="contact")


]

Django_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Django_website.apps.public.urls')),
    path('accounts/', include('Django_website.apps.accounts.urls')),
    path('contact/', include('Django_website.apps.contact.urls')),

    #Django Auth
    path('accounts/login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout')

]

Django_website/apps/accounts/models.py
from django.db import models
from django.db.models.fields import URLField
from django.contrib.auth.models import User
from django.utils.regex_helper import normalize

# Create your models here.

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class UserProfile(models.Model):
    #owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    
    #settings
    is_full_name_displayed = models.BooleanField(default=True)

    #Details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

Django_website/apps/contact/models.py
from django.db import models

# Create your models here.

Django_website/apps/contact/forms.py
from django import forms
from django.forms.fields import CharField

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Name'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Message', 'rows' : '5'}))

Django_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class ProfileView(LoginRequiredMixin ,TemplateView):
    template_name = 'accounts/profile.html'

Django_website/apps/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.core.mail import send_mail
from .forms import ContactForm
from Django_website import settings

# Create your views here.

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            send_mail(f"{name} send an email", message, email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form":form, "success":True})
    else:
        raise NotImplementedError
    return render(request, "contact.html", {"form":form})

Django_website/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock%}

Django_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<h2> Login </h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock%}

Django_website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}
<h1>
    Profile
</h1>
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 py-4">
                <div class="text-center"> <img src="https://www.tinygraphs.com/labs/isogrids/hexa16/helloworld?theme=bythepool&numcolors=4" width="100" class="rounded-circle"> </div>
                <div class="text-center mt-3">
                    <h5 class="mt-2 mb-0">{{user.get_full_name}} {{ user.username }}</h5> <span>Web Developer</span>
                    <div class="px-4 mt-1">
                        <p class="fonts">I am a self-motivated and creative
                            engineering student specialized in computer
                            science with keen interst in web development </p>
                    </div>
                    
                    <div class="social-list">
                        <a style="padding-left:20px;" href="https://www.facebook.com/profile.php?id=100004309635517"><i class="fab fa-facebook-f"></i></a>
                        <a style="padding-left:20px;" href="https://www.instagram.com/imen_zayani/"><i class="fab fa-instagram"></i></a>
                        <a style="padding-left:20px;" href="https://github.com/ImenZayani"><i class="fab fa-github"></i></a>
                        <a style="padding-left:20px;" href="https://www.linkedin.com/in/imen-zayani-37991b141/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    
                   
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

Django_website/templates/base.html
<!-- templates/base.html -->
{% load static %}

<DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>{% block title %} Welcome To My Website {% endblock %}</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
            <meta name="description" content="" />
            <meta name="author" content="" />

            <!-- Font Awesome icons (free version)-->
            <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
            <!-- Google fonts-->
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
            <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
            <!-- Core theme CSS (includes Bootstrap)-->
            <link href="{% static '/theme/css/styles.css' %}" rel="stylesheet" />

            <link href="{% static 'css/main.css' %}" rel="stylesheet" />

        </head>
        <body>
            {% include 'navbar.html' %}
            <main id="main">
                {% block content %}
                {% endblock%}
            </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static '/theme/js/scripts.js' %}"></script>
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </body>
    </html>

Django_website/templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<section class="page-section" id="contact">
<div class="container px-5 my-5">
    <div class="container">
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">GET IN TOUCH</h2>
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
        <div class="divider-custom-line"></div>
    </div>
    </div>
    <div class="text-center text-secondary mb-0">
        <p>
            We do our best to respond to emails, but we get so many that it's sometimes hard to respond to all of them. If you don't get a response, please don't take offense. 
        </p>
        <p> You can also send us an email at <a href="mailto:imen1.zayani1@gmail.com"> imen1.zayani1@gmail.com </a></p>
    </div>
        {% if success %}
        <div class="alert alert-success" role="alert">
            Your message was sent! Check you inbox for a response.
        </div>
        {% endif %}
    <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        {% for field in form %}
        <div class="form-floating mb-3">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
                <p class="help-block text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}
        
        <div class="d-grid">
            <button class="btn btn-primary btn-lg" id="submitButton" type="submit">Submit</button>
        </div>
        
    
    </form>
    
</div>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</section>
{% endblock%}

Django_website/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
<header class="masthead text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/logo.jpg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">We Make Things</h1>
        
    </div>
</header>
{% endblock%}

Django_website/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'accounts:profile' as profile_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:login' as login_url %}
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{{ index_url }}">Welcome</a>
            <button class="navbar-toggler text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == about_url %}active{% endif %}" href="{{ profile_url }}">Profile</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == about_url %}active{% endif %}" href="{{ logout_url }}">Logout</a></li>
                {% else %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded  {% if request.path == about_url %}active{% endif %}" href="{{ login_url }}">Login</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>


<!--        
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            <span> Hi {{ user.username }} !</span>
            <span><a href ="{% url 'logout' %}">Logout</a></span>
        {% else %}
            <span><a href ="{% url 'login' %}">Login</a></span>
        {% endif %}
    </span>
</nav>    -->